version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
